#!/bin/bash

DATABASE_HOST=${DATABASE_HOST:-mysql}
DATABASE_PORT=${DATABASE_PORT:-3306}
DATABASE_NAME=${DATABASE_NAME:-simpleci}
DATABASE_USER=${DATABASE_USER:-simpleci}
DATABASE_PASSWORD=${DATABASE_PASSWORD:-simpleci}

RABBITMQ_HOST=${RABBITMQ_HOST:-rabbitmq}
RABBITMQ_PORT=${RABBITMQ_PORT:-5672}
RABBITMQ_USER=${RABBITMQ_USER:-guest}
RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD:-guest}

REDIS_HOST=${REDIS_HOST:-redis}
REDIS_PORT=${REDIS_PORT:-6379}

CENTRIFUGO_HOST=${CENTRIFUGO_HOST:-localhost}
CENTRIFUGO_PORT=${CENTRIFUGO_PORT:-8000}

APP_LOCALE=${APP_LOCALE:-en}
SECRET=${SECRET:-some_secret_string}
APP_HOST=${APP_HOST:-simpleci.local}
